name: Build Electron App for Windows

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend/react-app
      - name: Install Electron dependencies
        run: npm install
        working-directory: electron
      - name: Build frontend
        run: npm run build
        working-directory: frontend/react-app
      - name: Build Electron app (Windows)
        run: |
          npm run build:frontend
          $env:CI = 'true'
          npx electron-builder --windows --publish never
        working-directory: electron
      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            electron/dist/*.exe
            electron/dist/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
